// Mocks generated by Mockito 5.4.4 from annotations
// in antioquia_bookstore/test/providers/books_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:antioquia_bookstore/api/store_api.dart' as _i2;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreApi extends _i1.Mock implements _i2.StoreApi {
  MockStoreApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void configureDio({_i3.Dio? dio}) => super.noSuchMethod(
        Invocation.method(
          #configureDio,
          [],
          {#dio: dio},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, dynamic>> httpGet(String? path) => (super.noSuchMethod(
        Invocation.method(
          #httpGet,
          [path],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
